# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='name',
        ),
    ]
