# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160627_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='days_off',
            field=models.ManyToManyField(blank=True, to='schedules.DayOfWeek'),
        ),
    ]
