# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160629_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='days_off',
        ),
    ]
