# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20160711_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
