# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_employeeprofile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
