# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0018_dayofweek'),
        ('profiles', '0011_auto_20160712_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='regular_days_off',
            field=models.ManyToManyField(to='schedules.DayOfWeek'),
        ),
    ]
