# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='availability',
            field=models.ManyToManyField(to='profiles.Available'),
        ),
    ]
