# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_employeeprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='availability',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Available'),
        ),
    ]
