# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20160717_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='regular_days_off',
            field=models.ManyToManyField(blank=True, null=True, to='schedules.DayOfWeek'),
        ),
    ]
