# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20160717_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='availability',
            field=models.ManyToManyField(blank=True, to='profiles.Available'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='regular_days_off',
            field=models.ManyToManyField(blank=True, to='schedules.DayOfWeek'),
        ),
    ]
