# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0026_auto_20160725_1241'),
        ('profiles', '0018_auto_20160717_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Department'),
            preserve_default=False,
        ),
    ]
