# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20160726_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Department'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Department'),
        ),
    ]
