# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20160726_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='was_invited',
            field=models.BooleanField(default=False),
        ),
    ]
