# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_employeeprofile_was_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
