language: python
python:
- 3.5.1
services:
- postgresql
env:
- DJANGO=1.9.7
before_install:
- export DJANGO_SETTINGS_MODULE=casino_schedule.travis-settings
- export PYTHONPATH=$HOME/builds/Aaron/CasinoScheduleApp
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE casino_schedules;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test schedules
- coverage run --source='.' manage.py test profiles
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: BbiBbuOpDkiTB3ymssx6KTZVM7pLXYr4yZMwHly6pkMi1XF+cxQEKiX5ICQU4uQ7wvCFMokCiLJKWegwCqORXRyMHPo6qbpZLYhYd+8V6CJX2p0OVs/yjnewuxvAWqys6KUah6uVz+pegATSE02zw4INjDySWjFEsEwnTMxKLS15FiSla/5Z0yhtEX9D5K0bqlA5YrY7NrRklSbvMLZxr3VMoSp0lekUqFo7idxssRuVZeKgmBKYfoyvUeYZAptFNsYQR/SzRINTu7B2r3Vr3jn/w/ZhA0vmIzRyxegBOH7vGNIXcRdsCxl2gWgtFniCZ1lkGSYVQg28vqTpYgoEeayPkk9qoKVK2kopiFQQoGdCt6Ol1A6gB/WNF4U/EF2K+IH2N/MCyDEHVvsCXfWgJP5O4jKsVqAIJlxOtkZg36snH7+Yw4VEh75sl+q17cKmGq8rPuF+IwjsxLhLxTR/3x5umU4GYNIWu17soMrtGYAXGoPOi2yvaM+qi/C2S3INNTHA6ee5k9xNBNThIx4n2pEEAWMwbPH2qK1eS9Lswh0FEBatnRp3IWEYqAqMpUufUV4eVyfHDLwFji75JpaWEx2rHvYLBn1R8BD7ayT1N4HsVibmOEARl1Mdql6BU9a/OUwtnC3ROCntg580Ka0BbxUZWErwX+M5fQfm06DVcXg=
  app: sheltered-springs-57964
    on:
    repo: CasinoSchedule/Schedule-API