# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20160623_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='date',
            new_name='day_date',
        ),
    ]
