# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20160623_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day_date',
            field=models.DateField(unique=True),
        ),
    ]
