# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20160623_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
