# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160624_1205'),
        ('schedules', '0005_auto_20160623_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField()),
                ('length', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.WorkDay')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.EmployeeProfile')),
            ],
        ),
    ]
