# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['day_date']},
        ),
    ]
