# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20160628_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
