# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_employeeprofile_days_off'),
        ('schedules', '0008_schedule_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='day_of_the_week',
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
    ]
