# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20160629_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
