# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_shift_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='submitted', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EOList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.WorkDay')),
            ],
        ),
        migrations.AddField(
            model_name='eoentry',
            name='eo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.EOList'),
        ),
        migrations.AddField(
            model_name='eoentry',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Shift'),
        ),
    ]
