# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20160709_1411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eoentry',
            unique_together=set([('shift', 'eo_list')]),
        ),
    ]
