# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20160711_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedules.Shift')),
            ],
        ),
    ]
