# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from schedules.models import Status

class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='callout',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Status'),
            preserve_default=False,
        ),
    ]
