# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_callout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callout',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Status'),
        ),
    ]
