# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20160717_1619'),
        ('schedules', '0020_callout_call_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(to='schedules.WorkDay')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.EmployeeProfile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Status')),
            ],
        ),
    ]
