# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0022_auto_20160720_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grave_start', models.TimeField(blank=True, null=True)),
                ('day_start', models.TimeField(blank=True, null=True)),
                ('swing_start', models.TimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Area')),
            ],
        ),
    ]
