# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0023_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='must_fill',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
