# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0027_shifttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='starting_time',
            field=models.TimeField(default="11:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='shift_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Available'),
        ),
    ]
