# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0028_auto_20160808_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplate',
            name='starting_time',
        ),
    ]
